### PR TITLE
fix rel for tiling-scheme and openapi media-type

### LINKED ISSUE #226: Returned `rel` link for tiling scheme is wrong
While I was trying to check the OpenLayers demo [https://openlayers.org/en/latest/examples/ogc-vector-tiles.html](https://openlayers.org/en/latest/examples/ogc-vector-tiles.html) out with an online TiPG deployment https://jcaujxxvec.execute-api.eu-west-1.amazonaws.com/api/docs I realize the following:

- Using `https://jcaujxxvec.execute-api.eu-west-1.amazonaws.com/api/collections/adam.adam_ts_tracks/tiles/WebMercatorQuad` as the `url` value for the `OGCVectorTile` the demo doesn't work as expected
- After a bit of debugging on the client code I have figured out that this exception is raised
   ```javascript
   throw new Error(
      "Expected http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme link or tileMatrixSet"
    );
    ````
- After a further analysis on the payloads returned by TiPG I have found that the endpoints with the tiling scheme return a `rel` link with the plural form of the IRI tiling scheme `http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes` while OL expects clearly the singular form `http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme` according to [https://docs.ogc.org/is/20-057/20-057.html#toc30](https://docs.ogc.org/is/20-057/20-057.html#toc30) section `8.2.2` Requirement 8 Identifier D and confirmed by the exception

Image

### PR DESCRIPTION
**Pull request by vincentsarago**
closes #226

### CODE REVIEW

File: examples/ol/main.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import VectorTileLayer from 'ol/layer/VectorTile.js';
+import OGCVectorTile from 'ol/source/OGCVectorTile.js';
+
+const map = new Map({
+  target: 'map',
+  layers: [
+    new VectorTileLayer({
+      source: new OGCVectorTile({
+        url: 'http://127.0.0.1:8081/collections/public.countries/tiles/WebMercatorQuad',
+        context: {"z": "tileMatrix", "y": "tileRow", "x": "tileCol"},
```
Comment (vincentsarago) [inline examples/ol/main.js:13]: @francbartoli do you know how it works to tell ol to use `Z/X/Y` instead of `tileMatrix/tileRow/tileCol` ?

**Comment by vincentsarago** [comment]
ok I'm going to remove the example and assume the issue is fixed
